Add isssue template referring to discussions
notaryproject/nv2 pull request #23
Opened 2021-01-13 17:28 UTC by marcofranssen

This PR adds a reference to Github discussions when someone tries to create a new issue.

Didn't define templates yet so kept free format issues open for now.

Defining templates allows for automation using github actions. E.g. Agenda items to discuss in meetings etc.

2021-03-27 00:40 UTC, SteveLasker commented
oh, this looks good. Need to look at again, and see if we should apply to all repos.
We also need a better map for which repos do what: https://github.com/notaryproject/notaryproject/issues/51

2021-04-04 02:49 UTC, SteveLasker requested changes

2021-04-04 02:49 UTC, SteveLasker commented on .github/ISSUE_TEMPLATE/config.yml
> +    url: https://github.com/notary-project/nv2/discussions
typo in the url for notary**-**project:
Should be:
https://github.com/notaryproject/nv2/discussions

2021-04-06 12:32 UTC, marcofranssen commented
@SteveLasker rebased on top of main branch and resolved the typo.

2021-04-06 23:46 UTC, SteveLasker approved these changes
LGTM, thanks @marcofranssen

2021-04-26 21:09 UTC, SteveLasker approved these changes
LGTM

2021-04-26 21:10 UTC, merged